In [35]:
import json
import os
import pickle
from skimage import io
import numpy as np
import torch

In [2]:
with open(os.path.join("D:\Projects\Pixel2Mesh-1\datasets\data\shapenet", "meta", "shapenet.json"), "r") as fp:
    # a=json.load(fp)
    # print
    labels_map = sorted(list(json.load(fp).keys()))

print(labels_map)

print(enumerate(labels_map))

labels_map = {i:k for i, k in enumerate(labels_map)}

print(labels_map)

['02691156', '02828884', '02933112', '02958343', '03001627', '03211117', '03636649', '03691459', '04090263', '04256520', '04379243', '04401088', '04530566']
{0: '02691156', 1: '02828884', 2: '02933112', 3: '02958343', 4: '03001627', 5: '03211117', 6: '03636649', 7: '03691459', 8: '04090263', 9: '04256520', 10: '04379243', 11: '04401088', 12: '04530566'}


In [4]:
with open(os.path.join("D:\Projects\Pixel2Mesh-1\datasets\data\shapenet", "meta", "test_small.txt"), "r") as fp:
    file_names = fp.read().split("\n")

print(type(file_names))
print(file_names[-10:-1])
print(file_names[-10:-1])
print(file_names[-10:])

<class 'list'>
['02691156_fff513f407e00e85a9ced22d91ad7027_14.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_15.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_16.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_17.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_18.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_19.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_20.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_21.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_22.dat']
['02691156_fff513f407e00e85a9ced22d91ad7027_14.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_15.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_16.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_17.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_18.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_19.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_20.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_21.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_22.dat']
['02691156_fff513f407e00e85a9ced22d91ad7027_14.

In [28]:
L = list(range(10))
print(L)
print(L[:9])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
pkl_path ="D:/Projects/Pixel2Mesh-1\datasets\data\shapenet\data_tf/02691156/fff513f407e00e85a9ced22d91ad7027/rendering/00.dat"

#with open(pkl_path) as f:
data = pickle.load(open(pkl_path, 'rb'), encoding="latin1")
pts, normals = data[:, :3], data[:, 3:]
print(pts.shape)
print(pts)
print(normals.shape)

(8096, 3)
[[-0.03563542  0.05891569 -0.89526075]
 [-0.05031313  0.06098781 -0.8937496 ]
 [-0.04333718  0.074516   -0.8918777 ]
 ...
 [ 0.02759777 -0.05798382 -0.68825823]
 [ 0.03280783 -0.06926504 -0.68265325]
 [ 0.03412661 -0.07334752 -0.6806949 ]]
(8096, 3)


In [26]:
img = io.imread("D:\Projects\Pixel2Mesh-1\datasets\data\shapenet\data_tf/02691156/fff513f407e00e85a9ced22d91ad7027/rendering/00.png")
print(img.shape)
#img[np.where(img[:, :, 3] == 0)] = 255
print(img.shape)

(137, 137, 4)
(137, 137, 4)


In [30]:
"%.6f (%.6f)" % (1,5)

'1.000000 (5.000000)'

In [42]:
with open("D:\Projects\Pixel2Mesh-1\datasets\data\ellipsoid\info_ellipsoid.dat", "rb") as fp:
    fp_info = pickle.load(fp, encoding='latin1')
print(type(fp_info))
print(fp_info[0])
coord = torch.tensor(fp_info[0]) #- torch.tensor(mesh_pos, dtype=torch.float)
print(coord.shape)

<class 'tuple'>
[[-0.1475   -0.1475   -0.876884]
 [-0.1475   -0.161837 -0.845   ]
 [-0.176174 -0.1475   -0.845   ]
 [-0.1475   -0.164438 -0.7675  ]
 [-0.181376 -0.1475   -0.7675  ]
 [-0.1475   -0.1475   -0.723224]
 [-0.07     -0.1475   -0.924942]
 [-0.07     -0.149614 -0.9225  ]
 [-0.077241 -0.1475   -0.9225  ]
 [-0.07     -0.184463 -0.845   ]
 [-0.07     -0.187064 -0.7675  ]
 [-0.103966 -0.1475   -0.69    ]
 [-0.07     -0.157416 -0.69    ]
 [-0.07     -0.1475   -0.677584]
 [ 0.0075   -0.1475   -0.932452]
 [ 0.0075   -0.156116 -0.9225  ]
 [ 0.0075   -0.190965 -0.845   ]
 [ 0.0075   -0.193565 -0.7675  ]
 [ 0.0075   -0.163918 -0.69    ]
 [ 0.0075   -0.1475   -0.669443]
 [ 0.076892 -0.1475   -0.9225  ]
 [ 0.085    -0.1475   -0.920261]
 [ 0.085    -0.181342 -0.845   ]
 [ 0.085    -0.183943 -0.7675  ]
 [ 0.085    -0.154295 -0.69    ]
 [ 0.085    -0.1475   -0.681492]
 [ 0.1625   -0.1475   -0.863004]
 [ 0.1625   -0.155596 -0.845   ]
 [ 0.1625   -0.158196 -0.7675  ]
 [ 0.1625   -0.1475   -0.73

In [2]:
import json
import os
import random
import shutil

In [12]:
with open("D:\Projects\Pixel2Mesh-1\datasets\data\shapenet\meta\shapenet.json") as fp:
    labels_map = json.load(fp)

print(type(labels_map))
print(labels_map)

<class 'dict'>
{'04256520': {'id': '04256520', 'name': 'sofa,couch,lounge'}, '02691156': {'id': '02691156', 'name': 'airplane,aeroplane,plane'}, '03636649': {'id': '03636649', 'name': 'lamp'}, '04401088': {'id': '04401088', 'name': 'telephone,phone,telephone set'}, '04530566': {'id': '04530566', 'name': 'vessel,watercraft'}, '03691459': {'id': '03691459', 'name': 'loudspeaker,speaker,speaker unit,loudspeaker system,speaker system'}, '03001627': {'id': '03001627', 'name': 'chair'}, '02933112': {'id': '02933112', 'name': 'cabinet'}, '04379243': {'id': '04379243', 'name': 'table'}, '03211117': {'id': '03211117', 'name': 'display,video display'}, '02958343': {'id': '02958343', 'name': 'car,auto,automobile,machine,motorcar'}, '02828884': {'id': '02828884', 'name': 'bench'}, '04090263': {'id': '04090263', 'name': 'rifle'}}


In [ ]:
with open("D:\Projects\Pixel2Mesh-1\datasets\data\shapenet\meta/test_tf.txt") as fp:
    lines = [line.strip() for line in fp.readlines()]

print(type(lines))
print(lines)

In [ ]:
print(labels_map.values)
for entry in labels_map.values():

    file_list = list(filter(lambda x: (entry["id"] + "/") in x, lines))
    #随机选择一个file
    chosen = random.choice(file_list)
    file_location = os.path.join("D:\Projects\Pixel2Mesh-1\datasets/data/shapenet/data_tf",
                                 chosen[len("Data/ShapeNetP2M/"):-4] + ".png")
    print(file_location)
    shutil.copyfile(file_location, "D:\Projects\Pixel2Mesh-1\datasets/examples/%s.png" % entry["name"].split(",")[0])