In [35]:
import json
import os
import pickle
from skimage import io
import numpy as np
import torch

In [2]:
with open(os.path.join("D:\Projects\Pixel2Mesh-1\datasets\data\shapenet", "meta", "shapenet.json"), "r") as fp:
    # a=json.load(fp)
    # print
    labels_map = sorted(list(json.load(fp).keys()))

print(labels_map)

print(enumerate(labels_map))

labels_map = {i:k for i, k in enumerate(labels_map)}

print(labels_map)

['02691156', '02828884', '02933112', '02958343', '03001627', '03211117', '03636649', '03691459', '04090263', '04256520', '04379243', '04401088', '04530566']
{0: '02691156', 1: '02828884', 2: '02933112', 3: '02958343', 4: '03001627', 5: '03211117', 6: '03636649', 7: '03691459', 8: '04090263', 9: '04256520', 10: '04379243', 11: '04401088', 12: '04530566'}


In [4]:
with open(os.path.join("D:\Projects\Pixel2Mesh-1\datasets\data\shapenet", "meta", "test_small.txt"), "r") as fp:
    file_names = fp.read().split("\n")

print(type(file_names))
print(file_names[-10:-1])
print(file_names[-10:-1])
print(file_names[-10:])

<class 'list'>
['02691156_fff513f407e00e85a9ced22d91ad7027_14.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_15.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_16.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_17.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_18.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_19.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_20.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_21.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_22.dat']
['02691156_fff513f407e00e85a9ced22d91ad7027_14.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_15.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_16.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_17.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_18.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_19.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_20.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_21.dat', '02691156_fff513f407e00e85a9ced22d91ad7027_22.dat']
['02691156_fff513f407e00e85a9ced22d91ad7027_14.

In [28]:
L = list(range(10))
print(L)
print(L[:9])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 1, 2, 3, 4, 5, 6, 7, 8]


In [17]:
pkl_path ="D:/Projects/Pixel2Mesh-1\datasets\data\shapenet\data_tf/02691156/fff513f407e00e85a9ced22d91ad7027/rendering/00.dat"

#with open(pkl_path) as f:
data = pickle.load(open(pkl_path, 'rb'), encoding="latin1")
pts, normals = data[:, :3], data[:, 3:]
print(pts.shape)
print(pts)
print(normals.shape)

(8096, 3)
[[-0.03563542  0.05891569 -0.89526075]
 [-0.05031313  0.06098781 -0.8937496 ]
 [-0.04333718  0.074516   -0.8918777 ]
 ...
 [ 0.02759777 -0.05798382 -0.68825823]
 [ 0.03280783 -0.06926504 -0.68265325]
 [ 0.03412661 -0.07334752 -0.6806949 ]]
(8096, 3)


In [26]:
img = io.imread("D:\Projects\Pixel2Mesh-1\datasets\data\shapenet\data_tf/02691156/fff513f407e00e85a9ced22d91ad7027/rendering/00.png")
print(img.shape)
#img[np.where(img[:, :, 3] == 0)] = 255
print(img.shape)

(137, 137, 4)
(137, 137, 4)


In [30]:
"%.6f (%.6f)" % (1,5)

'1.000000 (5.000000)'

In [41]:
with open("D:\Projects\Pixel2Mesh-1\datasets\data\ellipsoid\info_ellipsoid.dat", "rb") as fp:
    fp_info = pickle.load(fp, encoding='latin1')
print(type(fp_info))
print(fp_info[0])
coord = torch.tensor(fp_info[0]) #- torch.tensor(mesh_pos, dtype=torch.float)
print(coord.shape)

<class 'tuple'>
torch.Size([156, 3])
